### ISSUE TITLE
Configure does not work

### ISSUE THREAD

**Issue by obromios** [choonkeat/active_params#4]
This gem could save me a lot of times in upgrading from rails 4 to rail 5.  I am using ```protectect_attributes``` but this is no longer supported in rail 4. I would like to use my feature spec tests to discover all the strong parameters declarations.  I have tried the following

```
ActiveParams.config do |config|
  config.writing = Rails.env.test?
end
```
but I get the following error
`/config/initializers/active_params.rb:1:in `<top (required)>': undefined method `config' for ActiveParams:Module (NoMethodError)`

I have temporarily worked around this by cloning the gem and changing line 33 or ```lib/active_params.rb```.

 If there is not a simple fix, would you like me to have to have a go at a pull request with a fix?

**Comment by choonkeat** [comment]
It's because I didn't push the latest code (as per README) to rubygems as v1.0.0. Please `bundle update active_params`, see that it upgrades to `1.0.0` and try again? 🙏

**Comment by obromios** [comment]
I have done as you suggested, and it works now.

Thank you.
